-- AlterTable
ALTER TABLE "Rides" ALTER COLUMN "distance" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "duration" SET DATA TYPE TEXT,
ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "customer_id" SET DATA TYPE TEXT;
